Flowpack:
  Neos:
    Matomo:
      host: ''
      protocol: https
      token_auth: ''
      idSite: ''
      apiTimeout: 10

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Flowpack.Neos.Matomo:
            - 'NodeTypes/*'
    modules:
      seo:
        label: SEO
        icon: icon-rocket
        submodules:
          matomo:
            label: Matomo
            controller: \Flowpack\Neos\Matomo\Controller\Module\MatomoController
            description: 'Configure Matomo for your Domains'
            icon: icon-bar-chart
            actions:
              index:
                label: 'Configure Matomo'
                title: 'Configure Matomo'
    fusion:
      autoInclude:
        Flowpack.Neos.Matomo: true
