
Portachtzig:
  Neos:
    Piwik:
      host: piwik.portachtzig.com
      token_auth: 40a75d4453f97fa7d6cc0091647d4294
      idSite: '4'
TYPO3:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Portachtzig.Neos.Piwik:
            - 'NodeTypes/*'
    modules:
      seo:
        label: SEO
        icon: icon-rocket
        submodules:
          piwik:
            label: Piwik
            controller: \Portachtzig\Neos\Piwik\Controller\Module\PiwikController
            description: 'Configure Piwik for your Domains'
            icon: icon-bar-chart
            actions:
              index:
                label: 'Configure piwik'
                title: 'Configure piwik'
    typoScript:
      autoInclude:
        Portachtzig.Neos.Piwik: true
