Flowpack:
  Neos:
    Matomo:
      host: ''
      protocol: https
      system: matomo
      token_auth: ''
      idSite: ''
      containerId: ''
      apiTimeout: 10
      cacheLifetimeByPeriod:
        year: 86400
        day: 3600
      privacyManagement:
        disableCookies: false # this disables all cookies. See https://matomo.org/faq/general/faq_157/
        requireTrackingConsent: false # requires user's tracking consent before making tracking calls to matomo. See https://developer.matomo.org/guides/tracking-consent
        requireCookieConsent: false # requires user's consent before setting cookies. See https://developer.matomo.org/guides/tracking-consent

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Flowpack.Neos.Matomo:
            - 'NodeTypes/*'
    modules:
      seo:
        label: SEO
        icon: icon-rocket
        submodules:
          matomo:
            label: Matomo
            controller: \Flowpack\Neos\Matomo\Controller\Module\MatomoController
            description: 'Configure Matomo for your Domains'
            icon: icon-bar-chart
            actions:
              index:
                label: 'Configure Matomo'
                title: 'Configure Matomo'
    fusion:
      autoInclude:
        Flowpack.Neos.Matomo: true
